string  path            # The path of the audio file translated
string  model           # The name of the model used
float32 temperature     # The sampling temperature between 0 and 1
string  prompt          # An English text to guide the model's style or an empty string to use default
string  response_format # The translation format in json, text, srt, verbose_json, vtt, or diarized_json
---
bool    success         # Indicates the success or failure of the service call
string  message         # A natural language summary of the service call outcome
string  translation     # The resulting translation object